### ISSUE TITLE
Can I use GPU accelerate the training process?

### ISSUE THREAD

**Issue by ConanCui** [Mehran-k/SimplE#3]
The training process (except the early stop process and test process) take me 7 hours on wn18 dataset using the default parameters on a Linux machine (One GTX 1080 ti). Is this normal?

And I find the early stop process also need 6 hours on wn18 dataset, I guess the time consuming is mainly from "self.reader.replace_raw" and "get_rank" step. Is this normal?

**Comment by Mehran-k** [comment]
Yes, the timings seem normal to me (I was using a Titan Xp and if I remember correctly, it was a bit faster for me, but not much). 
Upon a few requests, I'm developing a PyTorch version of SimplE which will be (probably) faster than the one here. Stay tuned!

**Comment by Mehran-k** [comment]
A much faster version (in PyTorch) is available here: https://github.com/baharefatemi/SimplE
Closing the issue.
